-- =============================================================================
-- ENUMS
-- =============================================================================

CREATE TYPE user_role AS ENUM ('CANDIDATE', 'RECRUITER');
CREATE TYPE job_status AS ENUM ('OPEN', 'CLOSED', 'CANCELLED');
CREATE TYPE question_difficulty AS ENUM ('BEGINNER', 'INTERMEDIATE', 'ADVANCED');
CREATE TYPE question_source AS ENUM ('INTERNAL', 'AI_GENERATED');
CREATE TYPE test_status AS ENUM ('IN_PROGRESS', 'COMPLETED', 'CANCELED');
CREATE TYPE proficiency_level AS ENUM ('BASIC', 'INTERMEDIATE', 'ADVANCED', 'FLUENT', 'NATIVE');

-- =============================================================================
-- GEOLOCATION & ADDRESSES
-- =============================================================================

CREATE TABLE countries
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name        TEXT        NOT NULL,
    code_alpha2 VARCHAR(2)  NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_countries PRIMARY KEY (id),
    CONSTRAINT uq_countries_name UNIQUE (name),
    CONSTRAINT uq_countries_alpha2 UNIQUE (code_alpha2)
);

CREATE TABLE states
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    country_id INTEGER     NOT NULL,
    name       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_states PRIMARY KEY (id),
    CONSTRAINT fk_states_country FOREIGN KEY (country_id) REFERENCES countries (id)
);

CREATE TABLE cities
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    state_id   INTEGER     NOT NULL,
    name       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_cities PRIMARY KEY (id),
    CONSTRAINT fk_cities_state FOREIGN KEY (state_id) REFERENCES states (id)
);

CREATE TABLE addresses
(
    id           UUID DEFAULT uuidv7(),
    city_id      INTEGER     NOT NULL,
    zip_code     VARCHAR(20),
    street       TEXT        NOT NULL,
    number       VARCHAR(50),
    neighborhood TEXT,
    complement   TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_addresses PRIMARY KEY (id),
    CONSTRAINT fk_addresses_city FOREIGN KEY (city_id) REFERENCES cities (id)
);

CREATE INDEX idx_addresses_city_id ON addresses (city_id);

-- =============================================================================
-- CORE & DOMAINS
-- =============================================================================

CREATE TABLE users
(
    id              UUID DEFAULT uuidv7(),
    name            TEXT        NOT NULL,
    email           TEXT        NOT NULL,
    password        TEXT        NOT NULL,
    role            user_role   NOT NULL,
    document_type   VARCHAR(20),
    document_number VARCHAR(50),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_document UNIQUE (document_type, document_number)
);

CREATE TABLE companies
(
    id         UUID DEFAULT uuidv7(),
    address_id UUID,
    name       TEXT        NOT NULL,
    cnpj       VARCHAR(14),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT pk_companies PRIMARY KEY (id),
    CONSTRAINT uq_companies_cnpj UNIQUE (cnpj),
    CONSTRAINT fk_companies_address FOREIGN KEY (address_id) REFERENCES addresses (id)
);

CREATE TABLE technologies
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       TEXT        NOT NULL,
    category   TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_technologies PRIMARY KEY (id),
    CONSTRAINT uq_technologies_name UNIQUE (name)
);

CREATE TABLE languages
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_languages PRIMARY KEY (id),
    CONSTRAINT uq_languages_name UNIQUE (name)
);

-- =============================================================================
-- RECRUITERS & CANDIDATES
-- =============================================================================

CREATE TABLE recruiters
(
    id         UUID DEFAULT uuidv7(),
    user_id    UUID        NOT NULL,
    company_id UUID        NOT NULL,
    department TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT pk_recruiters PRIMARY KEY (id),
    CONSTRAINT uq_recruiters_user UNIQUE (user_id),
    CONSTRAINT fk_recruiters_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_recruiters_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE INDEX idx_recruiters_company_id ON recruiters (company_id);

CREATE TABLE candidates
(
    id         UUID DEFAULT uuidv7(),
    user_id    UUID        NOT NULL,
    address_id UUID,
    phone      VARCHAR(20),
    summary    TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT pk_candidates PRIMARY KEY (id),
    CONSTRAINT uq_candidates_user UNIQUE (user_id),
    CONSTRAINT fk_candidates_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_candidates_address FOREIGN KEY (address_id) REFERENCES addresses (id)
);

CREATE TABLE candidate_links
(
    id           UUID DEFAULT uuidv7(),
    candidate_id UUID        NOT NULL,
    name         VARCHAR(50) NOT NULL,
    url          TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_candidate_links PRIMARY KEY (id),
    CONSTRAINT fk_candidate_links_candidate FOREIGN KEY (candidate_id) REFERENCES candidates (id)
);

CREATE INDEX idx_candidate_links_candidate_id ON candidate_links (candidate_id);

-- =============================================================================
-- CANDIDATE BACKGROUND (RESUME DATA)
-- =============================================================================

CREATE TABLE candidate_languages
(
    candidate_id UUID              NOT NULL,
    language_id  INTEGER           NOT NULL,
    proficiency  proficiency_level NOT NULL,
    CONSTRAINT pk_candidate_languages PRIMARY KEY (candidate_id, language_id),
    CONSTRAINT fk_candidate_languages_candidate FOREIGN KEY (candidate_id) REFERENCES candidates (id),
    CONSTRAINT fk_candidate_languages_language FOREIGN KEY (language_id) REFERENCES languages (id)
);

CREATE INDEX idx_candidate_languages_lang_id ON candidate_languages (language_id);

CREATE TABLE experiences
(
    id           UUID DEFAULT uuidv7(),
    candidate_id UUID        NOT NULL,
    title        TEXT        NOT NULL,
    company_name TEXT        NOT NULL,
    start_date   DATE        NOT NULL,
    end_date     DATE,
    is_current   BOOLEAN     NOT NULL DEFAULT FALSE,
    description  TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ,
    CONSTRAINT pk_experiences PRIMARY KEY (id),
    CONSTRAINT fk_experiences_candidate FOREIGN KEY (candidate_id) REFERENCES candidates (id)
);

CREATE INDEX idx_experiences_candidate_id ON experiences (candidate_id);

CREATE TABLE experience_technologies
(
    experience_id UUID    NOT NULL,
    technology_id INTEGER NOT NULL,
    CONSTRAINT pk_experience_technologies PRIMARY KEY (experience_id, technology_id),
    CONSTRAINT fk_exp_tech_experience FOREIGN KEY (experience_id) REFERENCES experiences (id),
    CONSTRAINT fk_exp_tech_technology FOREIGN KEY (technology_id) REFERENCES technologies (id)
);

CREATE TABLE educations
(
    id              UUID DEFAULT uuidv7(),
    candidate_id    UUID        NOT NULL,
    institution     TEXT        NOT NULL,
    field_of_study  TEXT        NOT NULL,
    degree          TEXT,
    start_date      DATE,
    completion_date DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT pk_educations PRIMARY KEY (id),
    CONSTRAINT fk_educations_candidate FOREIGN KEY (candidate_id) REFERENCES candidates (id)
);

CREATE INDEX idx_educations_candidate_id ON educations (candidate_id);

CREATE TABLE education_technologies
(
    education_id  UUID    NOT NULL,
    technology_id INTEGER NOT NULL,
    CONSTRAINT pk_education_technologies PRIMARY KEY (education_id, technology_id),
    CONSTRAINT fk_edu_tech_education FOREIGN KEY (education_id) REFERENCES educations (id),
    CONSTRAINT fk_edu_tech_technology FOREIGN KEY (technology_id) REFERENCES technologies (id)
);

CREATE TABLE certifications
(
    id                   UUID DEFAULT uuidv7(),
    candidate_id         UUID        NOT NULL,
    name                 TEXT        NOT NULL,
    issuing_organization TEXT        NOT NULL,
    issue_date           DATE,
    expiration_date      DATE,
    credential_url       TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at           TIMESTAMPTZ,
    CONSTRAINT pk_certifications PRIMARY KEY (id),
    CONSTRAINT fk_certifications_candidate FOREIGN KEY (candidate_id) REFERENCES candidates (id)
);

CREATE INDEX idx_certifications_candidate_id ON certifications (candidate_id);

CREATE TABLE projects
(
    id           UUID DEFAULT uuidv7(),
    candidate_id UUID        NOT NULL,
    name         TEXT        NOT NULL,
    description  TEXT,
    project_url  TEXT,
    start_date   DATE,
    end_date     DATE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT fk_projects_candidate FOREIGN KEY (candidate_id) REFERENCES candidates (id)
);

CREATE INDEX idx_projects_candidate_id ON projects (candidate_id);

CREATE TABLE project_technologies
(
    project_id    UUID    NOT NULL,
    technology_id INTEGER NOT NULL,
    CONSTRAINT pk_project_technologies PRIMARY KEY (project_id, technology_id),
    CONSTRAINT fk_proj_tech_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_proj_tech_technology FOREIGN KEY (technology_id) REFERENCES technologies (id)
);

-- =============================================================================
-- JOBS
-- =============================================================================

CREATE TABLE jobs
(
    id              UUID DEFAULT uuidv7(),
    recruiter_id    UUID           NOT NULL,
    company_id      UUID           NOT NULL,
    title           TEXT           NOT NULL,
    description     TEXT           NOT NULL,
    seniority_level TEXT,
    department      TEXT,
    salary_min      DECIMAL(10, 2),
    salary_max      DECIMAL(10, 2),
    status          job_status     NOT NULL DEFAULT 'OPEN',
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT pk_jobs PRIMARY KEY (id),
    CONSTRAINT fk_jobs_recruiter FOREIGN KEY (recruiter_id) REFERENCES recruiters (id),
    CONSTRAINT fk_jobs_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE INDEX idx_jobs_recruiter_id ON jobs (recruiter_id);
CREATE INDEX idx_jobs_company_id ON jobs (company_id);
CREATE INDEX idx_jobs_status ON jobs (status);

CREATE TABLE job_technologies
(
    job_id        UUID    NOT NULL,
    technology_id INTEGER NOT NULL,
    is_mandatory  BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_job_technologies PRIMARY KEY (job_id, technology_id),
    CONSTRAINT fk_job_tech_job FOREIGN KEY (job_id) REFERENCES jobs (id),
    CONSTRAINT fk_job_tech_technology FOREIGN KEY (technology_id) REFERENCES technologies (id)
);

-- =============================================================================
-- ASSESSMENTS & QUESTIONS
-- =============================================================================

CREATE TABLE questions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    technology_id    INTEGER             NOT NULL,
    statement        TEXT                NOT NULL,
    difficulty_level question_difficulty NOT NULL,
    source           question_source     NOT NULL DEFAULT 'INTERNAL',
    created_at       TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT pk_questions PRIMARY KEY (id),
    CONSTRAINT fk_questions_technology FOREIGN KEY (technology_id) REFERENCES technologies (id)
);

CREATE INDEX idx_questions_technology_id ON questions (technology_id);

CREATE TABLE question_options
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_id BIGINT      NOT NULL,
    option_text TEXT        NOT NULL,
    is_correct  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_question_options PRIMARY KEY (id),
    CONSTRAINT fk_question_options_question FOREIGN KEY (question_id) REFERENCES questions (id)
);

CREATE INDEX idx_question_options_question_id ON question_options (question_id);

CREATE TABLE tests
(
    id            UUID DEFAULT uuidv7(),
    candidate_id  UUID        NOT NULL,
    technology_id INTEGER     NOT NULL,
    status        test_status NOT NULL DEFAULT 'IN_PROGRESS',
    score         DECIMAL(5, 2),
    started_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT pk_tests PRIMARY KEY (id),
    CONSTRAINT fk_tests_candidate FOREIGN KEY (candidate_id) REFERENCES candidates (id),
    CONSTRAINT fk_tests_technology FOREIGN KEY (technology_id) REFERENCES technologies (id)
);

CREATE INDEX idx_tests_candidate_id ON tests (candidate_id);
CREATE INDEX idx_tests_technology_id ON tests (technology_id);
CREATE INDEX idx_tests_status ON tests (status);

CREATE TABLE candidate_answers
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    test_id            UUID        NOT NULL,
    question_id        BIGINT      NOT NULL,
    selected_option_id BIGINT,
    is_correct         BOOLEAN,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_candidate_answers PRIMARY KEY (id),
    CONSTRAINT uq_candidate_answers UNIQUE (test_id, question_id),
    CONSTRAINT fk_candidate_answers_test FOREIGN KEY (test_id) REFERENCES tests (id),
    CONSTRAINT fk_candidate_answers_question FOREIGN KEY (question_id) REFERENCES questions (id),
    CONSTRAINT fk_candidate_answers_option FOREIGN KEY (selected_option_id) REFERENCES question_options (id)
);

CREATE INDEX idx_candidate_answers_question_id ON candidate_answers (question_id);
CREATE INDEX idx_candidate_answers_selected_option ON candidate_answers (selected_option_id);

-- =============================================================================
-- GAMIFICATION & BADGES
-- =============================================================================

CREATE TABLE badges
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    technology_id INTEGER,
    name          TEXT        NOT NULL,
    description   TEXT,
    minimum_score DECIMAL(5, 2),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT pk_badges PRIMARY KEY (id),
    CONSTRAINT fk_badges_technology FOREIGN KEY (technology_id) REFERENCES technologies (id)
);

CREATE INDEX idx_badges_technology_id ON badges (technology_id);

CREATE TABLE candidate_badges
(
    candidate_id UUID        NOT NULL,
    badge_id     INTEGER     NOT NULL,
    test_id      UUID,
    earned_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_candidate_badges PRIMARY KEY (candidate_id, badge_id),
    CONSTRAINT fk_candidate_badges_candidate FOREIGN KEY (candidate_id) REFERENCES candidates (id),
    CONSTRAINT fk_candidate_badges_badge FOREIGN KEY (badge_id) REFERENCES badges (id),
    CONSTRAINT fk_candidate_badges_test FOREIGN KEY (test_id) REFERENCES tests (id)
);

CREATE INDEX idx_candidate_badges_badge_id ON candidate_badges (badge_id);
CREATE INDEX idx_candidate_badges_test_id ON candidate_badges (test_id);