openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/v1/companies/{id}:
    get:
      tags:
      - company-controller
      operationId: findById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseCompanyResponse"
    put:
      tags:
      - company-controller
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompanyRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseCompanyResponse"
    delete:
      tags:
      - company-controller
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseVoid"
  /api/v1/companies:
    get:
      tags:
      - company-controller
      operationId: findAll
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseListCompanyResponse"
    post:
      tags:
      - company-controller
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompanyRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseCompanyResponse"
  /api/v1/companies/{companyId}/recruiters:
    get:
      tags:
      - recruiter-controller
      operationId: findByCompanyId
      parameters:
      - name: companyId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseListRecruiterResponse"
    post:
      tags:
      - recruiter-controller
      operationId: linkToCompany
      parameters:
      - name: companyId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecruiterRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseRecruiterResponse"
  /api/v1/auth/register:
    post:
      tags:
      - auth-controller
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseRegisterResponse"
  /api/v1/auth/refresh:
    post:
      tags:
      - auth-controller
      operationId: refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseLoginResponse"
  /api/v1/auth/login:
    post:
      tags:
      - auth-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseLoginResponse"
  /api/v1/auth/complete-registration:
    patch:
      tags:
      - auth-controller
      operationId: completeRegistration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompleteRegistrationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseCompleteRegistrationResponse"
  /api/v1/recruiters/{id}:
    get:
      tags:
      - recruiter-controller
      operationId: findById_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BaseResponseRecruiterResponse"
components:
  schemas:
    CompanyRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        cnpj:
          type: string
      required:
      - name
    BaseResponseCompanyResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        result:
          $ref: "#/components/schemas/CompanyResponse"
        error:
          $ref: "#/components/schemas/ErrorResponse"
    CompanyResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        cnpj:
          type: string
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        validations:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
    ValidationError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
    RecruiterRequest:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        department:
          type: string
      required:
      - userId
    BaseResponseRecruiterResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        result:
          $ref: "#/components/schemas/RecruiterResponse"
        error:
          $ref: "#/components/schemas/ErrorResponse"
    RecruiterResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        companyId:
          type: string
          format: uuid
        department:
          type: string
    RegisterRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        email:
          type: string
          format: email
          minLength: 1
        password:
          type: string
          minLength: 1
      required:
      - email
      - name
      - password
    BaseResponseRegisterResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        result:
          $ref: "#/components/schemas/RegisterResponse"
        error:
          $ref: "#/components/schemas/ErrorResponse"
    RegisterResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string
          minLength: 1
      required:
      - refreshToken
    BaseResponseLoginResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        result:
          $ref: "#/components/schemas/LoginResponse"
        error:
          $ref: "#/components/schemas/ErrorResponse"
    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        registrationCompleted:
          type: boolean
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
        password:
          type: string
          minLength: 1
      required:
      - email
      - password
    CompleteRegistrationRequest:
      type: object
      properties:
        role:
          type: string
          enum:
          - CANDIDATE
          - RECRUITER
        documentType:
          type: string
        documentNumber:
          type: string
        phone:
          type: string
        summary:
          type: string
        companyId:
          type: string
          format: uuid
        department:
          type: string
      required:
      - role
    BaseResponseCompleteRegistrationResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        result:
          $ref: "#/components/schemas/CompleteRegistrationResponse"
        error:
          $ref: "#/components/schemas/ErrorResponse"
    CompleteRegistrationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
          - CANDIDATE
          - RECRUITER
        documentType:
          type: string
        documentNumber:
          type: string
    BaseResponseListCompanyResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        result:
          type: array
          items:
            $ref: "#/components/schemas/CompanyResponse"
        error:
          $ref: "#/components/schemas/ErrorResponse"
    BaseResponseListRecruiterResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        result:
          type: array
          items:
            $ref: "#/components/schemas/RecruiterResponse"
        error:
          $ref: "#/components/schemas/ErrorResponse"
    BaseResponseVoid:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        result: {}
        error:
          $ref: "#/components/schemas/ErrorResponse"
